server:
  port: 8889

spring:
  application:
    name: dm-service
  data:
    mongodb:
      uri: mongodb://34.64.48.95:27017/
      database: dm

management:
  endpoints:
    web:
      exposure:
        include: "*"
