server:
  port: 8889

spring:
  application:
    name: dm-service
  kafka:
    bootstrap-servers: http://34.64.48.95:9092
  cloud:
    config:
      enabled: true
    bus:
      enabled: true
      destination: config
  data:
    mongodb:
      uri: mongodb://34.64.48.95:27017/
      database: dm


management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  now: "dm-config 2023-08-07-18:20"