server:
  port: 8892

spring:
  application:
    name: feed-service
  kafka:
    bootstrap-servers: http://34.64.48.95:9092
  cloud:
    config:
      enabled: true
    bus:
      enabled: true
      destination: springCloudBus
  data:
    mongodb:
      uri: mongodb://34.64.48.95:27017/
      database: feed


