---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-container
          image: liardance/config-service:latest
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
  externalIPs:
    - 34.120.246.138
