---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-container
          image: liardance/auth-service:latest
          ports:
            - containerPort: 8890

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8890
      targetPort: 8890
  type: LoadBalancer
  externalIPs:
    - 34.64.48.95
