---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diary-service
  template:
    metadata:
      labels:
        app: diary-service
    spec:
      containers:
        - name: diary-container
          image: liardance/diary-service:latest
          ports:
            - containerPort: 8891

---
apiVersion: v1
kind: Service
metadata:
  name: diary-service
spec:
  selector:
    app: diary-service
  ports:
    - protocol: TCP
      port: 8891
      targetPort: 8891
  type: LoadBalancer
  externalIPs:
    - 34.64.48.95
